'''GENERAL'''
DEBUG_MODE = True

'''SERVO'''
SERVO_DEBUG_MODE = True
MIN_SERVO_DEG = 30
MAX_SERVO_DEG = 100
SERVO_CENTER_DEG = (MAX_SERVO_DEG + MIN_SERVO_DEG)/2


'''STEPPER'''
STEPPER_DEBUG_MODE = True
STEPPER_MAX_STEP_DEG =   # HOW MUCH?
STEPPER_MIN_STEP_DEG = -STEPPER_MAX_STEP_DEG
STEPPER_DT =   # HOW MUCH?
