'''GENERAL'''
DEBUG_MODE = False

'''SERVO'''
SERVO_DEBUG_MODE = True
SERVO_PORT = "/dev/ttyUSB1"
SERVO_MIN_DEG = 0
SERVO_MAX_DEG = 180
SERVO_CENTER_DEG = (SERVO_MAX_DEG + SERVO_MIN_DEG)/2
SERVO_MAX_DELTA = 25



'''STEPPER'''
STEPPER_DEBUG_MODE = False
STEPPER_PORT = "/dev/ttyUSB0"
STEPPER_MAX_STEP_DEG = 127  # HOW MUCH?
STEPPER_MIN_STEP_DEG = -STEPPER_MAX_STEP_DEG-1