'''GENERAL'''
DEBUG_MODE = False

'''SERVO'''
SERVO_DEBUG_MODE = False
SERVO_PORT = "/dev/ttyUSB0"
SERVO_MIN_DEG = 55
SERVO_MAX_DEG = 90
SERVO_CENTER_DEG = 70
SERVO_MAX_DELTA = 25
INIT_TIME = 2


'''STEPPER'''
STEPPER_DEBUG_MODE = True
STEPPER_PORT = "/dev/ttyUSB2"
STEPPER_MAX_STEP_DEG = 20#127  # HOW MUCH?
STEPPER_MIN_STEP_DEG = -STEPPER_MAX_STEP_DEG-1
STEPPER_BT_ADDR = "00:18:E4:0A:00:01"
STEPPER_BT_PORT = 1